sudo: false
language:
  - php
  - node_js

cache:
  directories:
    - node_modules
    - vendor

install:
  - npm install jshint jshint-stylish
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

script:
  - composer test
