sudo: false
language: php
php:
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g jshint jscs
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - jshint assets/src/js/*.js
  - jscs assets/src/js/
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
