sudo: false
language: php
php:
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - node_modules

install:
  - npm run setup
  - composer global require squizlabs/php_codesniffer

script:
  - npm run jshint
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
